### ISSUE TITLE
Key Features for the first Release

### ISSUE THREAD

**Issue by ethos05** [georgelemon/ego#2]
Nice to have (usability)

- [x] Small symbols that shows when the file is currently editing and needs to be saved
- [ ] Support for aligning (left, center, right) blocks with paragraphs and headlines
- [ ] Context menu: support for phrase search on search engines
- [ ] Prompt dialog on quit, prevent closing the app if the file has not  been saved
- [ ] Annotations support 
- [x] More intense highlight/marker colors
- [ ] Windows/Linux/Debian a better UI for scroll bar in order to replace the default one

**Comment by georgelemon** [comment]
Okay, we decide to leave some features for later. We can close this since is not related to the first release.
